same as creating trainset and testset. just doing the same thing for two semesters data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import datetime as dt
import pandas as pd
import torch

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [4]:
print(device)

cuda

In [15]:
file_path = '/content/drive/My Drive/001.PhD/Smartphone/Dataset/fall2020.csv'

In [16]:
data_frames = []

In [17]:
# Assuming file_paths contains a single file path string
dffall2020 = pd.read_csv(file_path, sep=';', low_memory=False)
data_frames.append(dffall2020)

In [18]:
# Merge the data frames into a single data frame
df_1 = pd.concat(data_frames, ignore_index=True)

In [19]:
df_1

,id,device_id,timestamp,action,extras,android_version,is_tablet
0,16,0c482c23bcc964f2,2020-10-21 17:16:00,android.intent.action.BATTERY_CHANGED,technology: Li-ionicon-small: 17303520max_char...,10,0
1,17,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.nsd.STATE_CHANGED,nsd_state: 2,10,0
2,18,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.conn.CONNECTIVITY_CHANGE,"networkInfo: [type: WIFI[], state: CONNECTED/C...",10,0
3,19,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.wifi.STATE_CHANGE,"networkInfo: [type: WIFI[], state: CONNECTED/C...",10,0
4,20,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.wifi.WIFI_STATE_CHANGED,previous_wifi_state: 2wifi_state: 3,10,0
...,...,...,...,...,...,...,...
7565101,7565117,4749291da46c42e3,2021-04-10 19:37:41,android.net.wifi.RSSI_CHANGED,newRssi: -67,11,0
7565102,7565118,4749291da46c42e3,2021-04-10 19:37:43,android.intent.action.BATTERY_CHANGED,technology: Li-ionicon-small: 17303549max_char...,11,0
7565103,7565119,4749291da46c42e3,2021-04-10 19:37:43,android.intent.action.DREAMING_STARTED,NaN,11,0
7565104,7565120,4749291da46c42e3,2021-04-10 19:37:43,android.intent.action.SCREEN_OFF,NaN,11,0
7565105,7565121,4749291da46c42e3,2021-04-10 19:37:52,android.intent.action.BATTERY_CHANGED,technology: Li-ionicon-small: 17303549max_char...,11,0

In [20]:
file_path_1 = '/content/drive/My Drive/001.PhD/Smartphone/Dataset/spring2022.csv'

In [21]:
data_frames = []

In [22]:
# Assuming file_paths contains a single file path string
dfspring2022 = pd.read_csv(file_path_1, sep=';', low_memory=False)
data_frames.append(dfspring2022)

In [23]:
# Merge the data frames into a single data frame
df_2 = pd.concat(data_frames, ignore_index=True)

In [24]:
df_2

,id,device_id,timestamp,action,extras,android_version,is_tablet
0,1,f403e06331460c63,2022-02-28 14:30:30,android.intent.action.BATTERY_CHANGED,technology: Li-ionicon-small: 17303567max_char...,12,0
1,2,f403e06331460c63,2022-02-28 14:30:30,android.intent.action.PROXY_CHANGE,android.intent.extra.PROXY_INFO: [] 0 xl=,12,0
2,3,f403e06331460c63,2022-02-28 14:30:30,android.net.nsd.STATE_CHANGED,nsd_state: 2,12,0
3,4,f403e06331460c63,2022-02-28 14:30:30,android.net.conn.CONNECTIVITY_CHANGE,"networkInfo: [type: MOBILE[LTE], state: CONNEC...",12,0
4,5,f403e06331460c63,2022-02-28 14:30:30,android.net.wifi.STATE_CHANGE,"networkInfo: [type: WIFI[], state: CONNECTED/C...",12,0
...,...,...,...,...,...,...,...
7504710,7505856,6edcf05bdae5b67e,2022-09-17 17:43:32,android.intent.action.BATTERY_CHANGED,current_event: 1073741824misc_event: 65536tech...,11,0
7504711,7505857,6edcf05bdae5b67e,2022-09-17 17:45:41,android.intent.action.DREAMING_STOPPED,NaN,11,0
7504712,7505858,6edcf05bdae5b67e,2022-09-17 17:45:41,android.intent.action.SCREEN_ON,why: 2,11,0
7504713,7505859,6edcf05bdae5b67e,2022-09-17 17:45:47,android.net.wifi.SCAN_RESULTS,resultsUpdated: true,11,0
7504714,7505860,6edcf05bdae5b67e,2022-09-17 17:45:57,android.net.wifi.SCAN_RESULTS,resultsUpdated: true,11,0

In [28]:
df = pd.concat([df_1, df_2], ignore_index=True)

In [29]:
df

,id,device_id,timestamp,action,extras,android_version,is_tablet
0,16,0c482c23bcc964f2,2020-10-21 17:16:00,android.intent.action.BATTERY_CHANGED,technology: Li-ionicon-small: 17303520max_char...,10,0
1,17,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.nsd.STATE_CHANGED,nsd_state: 2,10,0
2,18,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.conn.CONNECTIVITY_CHANGE,"networkInfo: [type: WIFI[], state: CONNECTED/C...",10,0
3,19,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.wifi.STATE_CHANGE,"networkInfo: [type: WIFI[], state: CONNECTED/C...",10,0
4,20,0c482c23bcc964f2,2020-10-21 17:16:00,android.net.wifi.WIFI_STATE_CHANGED,previous_wifi_state: 2wifi_state: 3,10,0
...,...,...,...,...,...,...,...
15069816,7505856,6edcf05bdae5b67e,2022-09-17 17:43:32,android.intent.action.BATTERY_CHANGED,current_event: 1073741824misc_event: 65536tech...,11,0
15069817,7505857,6edcf05bdae5b67e,2022-09-17 17:45:41,android.intent.action.DREAMING_STOPPED,NaN,11,0
15069818,7505858,6edcf05bdae5b67e,2022-09-17 17:45:41,android.intent.action.SCREEN_ON,why: 2,11,0
15069819,7505859,6edcf05bdae5b67e,2022-09-17 17:45:47,android.net.wifi.SCAN_RESULTS,resultsUpdated: true,11,0
15069820,7505860,6edcf05bdae5b67e,2022-09-17 17:45:57,android.net.wifi.SCAN_RESULTS,resultsUpdated: true,11,0

In [30]:
df = df.drop(columns=['id', 'extras', 'android_version', 'is_tablet'], axis=1)

In [31]:
dev_id = df['device_id'].unique()
len(dev_id)

105

In [32]:
df.count()

device_id    15069821
timestamp    15069821
action       15069821
dtype: int64

In [33]:
df=df.dropna()

In [34]:
df.count()

device_id    15069821
timestamp    15069821
action       15069821
dtype: int64

In [35]:
# Remove battery events
df = df.drop(df[df['action'].str.contains('BATTERY')].index)

In [36]:
df.count()

device_id    7404930
timestamp    7404930
action       7404930
dtype: int64

In [37]:
cols = ['device_id', 'action', 'timestamp']
df = df.reindex(columns = cols)

In [38]:
dev_id = df['device_id'].unique()
len(dev_id)

105

In [39]:
df.reset_index(inplace=True)
df = df.drop(columns=['index'], axis=1)
df

,device_id,action,timestamp
0,0c482c23bcc964f2,android.net.nsd.STATE_CHANGED,2020-10-21 17:16:00
1,0c482c23bcc964f2,android.net.conn.CONNECTIVITY_CHANGE,2020-10-21 17:16:00
2,0c482c23bcc964f2,android.net.wifi.STATE_CHANGE,2020-10-21 17:16:00
3,0c482c23bcc964f2,android.net.wifi.WIFI_STATE_CHANGED,2020-10-21 17:16:00
4,0c482c23bcc964f2,android.net.wifi.p2p.STATE_CHANGED,2020-10-21 17:16:00
...,...,...,...
7404925,6edcf05bdae5b67e,android.intent.action.SCREEN_OFF,2022-09-17 17:43:27
7404926,6edcf05bdae5b67e,android.intent.action.DREAMING_STOPPED,2022-09-17 17:45:41
7404927,6edcf05bdae5b67e,android.intent.action.SCREEN_ON,2022-09-17 17:45:41
7404928,6edcf05bdae5b67e,android.net.wifi.SCAN_RESULTS,2022-09-17 17:45:47
7404929,6edcf05bdae5b67e,android.net.wifi.SCAN_RESULTS,2022-09-17 17:45:57

In [40]:
df = df[df['timestamp'] != '0000-00-00 00:00:00'].copy()
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [41]:
dev_id = df['device_id'].unique()
len(dev_id)

104

In [42]:
df2 = df

In [43]:
# get device ids where user had device in phone atleast continous 30 days - quinn

# Convert the 'timestamp' column to datetime objects
df2['timestamp'] = pd.to_datetime(df2['timestamp'])

# Sort the DataFrame by 'device_id' and 'timestamp'
df2 = df.sort_values(by=['device_id', 'timestamp'])

# Calculate the difference between the maximum and minimum timestamp for each device
df2['time_range'] = df2.groupby('device_id')['timestamp'].transform('max') - df2.groupby('device_id')['timestamp'].transform('min')

# Define the time difference threshold for continuity (30 days)
continuity_threshold = pd.Timedelta(days=30)

# Filter the DataFrame to get devices where this difference is at least 30 days
at_least_30_days_data = df2[df2['time_range'] >= continuity_threshold]

In [44]:
dffinal = at_least_30_days_data.drop(columns=['time_range'], axis=1)

In [45]:
dffinal.head()

,device_id,action,timestamp
1237993,01413db4688c603c,android.net.nsd.STATE_CHANGED,2021-01-31 22:09:06
1237994,01413db4688c603c,android.net.conn.CONNECTIVITY_CHANGE,2021-01-31 22:09:06
1237995,01413db4688c603c,android.net.wifi.STATE_CHANGE,2021-01-31 22:09:06
1237996,01413db4688c603c,android.net.wifi.WIFI_STATE_CHANGED,2021-01-31 22:09:06
1237997,01413db4688c603c,android.net.wifi.p2p.STATE_CHANGED,2021-01-31 22:09:06

In [46]:
# converting time to seconds
dffinal['timestamp'] = pd.to_datetime(dffinal['timestamp'])
dffinal['timestamp'] = (dffinal['timestamp'] - dt.datetime(1970,1,1)).dt.total_seconds()

In [47]:
dffinal.head()

                device_id                                action     timestamp
1237993  01413db4688c603c         android.net.nsd.STATE_CHANGED  1.612131e+09
1237994  01413db4688c603c  android.net.conn.CONNECTIVITY_CHANGE  1.612131e+09
1237995  01413db4688c603c         android.net.wifi.STATE_CHANGE  1.612131e+09
1237996  01413db4688c603c   android.net.wifi.WIFI_STATE_CHANGED  1.612131e+09
1237997  01413db4688c603c    android.net.wifi.p2p.STATE_CHANGED  1.612131e+09

In [48]:
actions = dffinal['action'].unique()
len(actions)

77

In [49]:
dffinal = dffinal.drop_duplicates(subset = ['action', 'timestamp'], keep = 'first')

In [50]:
dffinal = dffinal.sort_values(by=['device_id', 'timestamp'], ascending=[True, True])

In [51]:
dffinal.reset_index(inplace=True)
dffinal = dffinal.drop(columns=['index'], axis=1)

In [52]:
dffinal = dffinal.groupby(['device_id', 'timestamp'])['action'].apply(list).reset_index(name = 'action')

In [54]:
dffinal

,device_id,timestamp,action
0,01413db4688c603c,1.612131e+09,"[android.net.nsd.STATE_CHANGED, android.net.co..."
1,01413db4688c603c,1.612131e+09,"[android.net.nsd.STATE_CHANGED, android.net.co..."
2,01413db4688c603c,1.612131e+09,"[android.intent.action.DREAMING_STARTED, andro..."
3,01413db4688c603c,1.612132e+09,[android.intent.action.DREAMING_STOPPED]
4,01413db4688c603c,1.612132e+09,"[android.net.wifi.RSSI_CHANGED, android.intent..."
...,...,...,...
1598944,fcff09aabf2a54a7,1.614796e+09,[android.net.wifi.RSSI_CHANGED]
1598945,fcff09aabf2a54a7,1.614796e+09,[android.net.wifi.RSSI_CHANGED]
1598946,fcff09aabf2a54a7,1.614796e+09,[android.net.wifi.RSSI_CHANGED]
1598947,fcff09aabf2a54a7,1.614796e+09,[android.net.wifi.RSSI_CHANGED]
1598948,fcff09aabf2a54a7,1.614796e+09,[android.net.wifi.RSSI_CHANGED]

In [55]:
minL = len(dffinal['action'].iloc[0])
maxL = len(dffinal['action'].iloc[0])
for i in range(1598949):
    curL = len(dffinal['action'].iloc[i])
    minL = min(minL, curL)
    maxL = max(maxL, curL)
print(minL)
print(maxL)

1
14

In [57]:
# making dataset
dataset = []

for i in range(1598949):
    if len(dffinal['action'].iloc[i]) > 1:
        dataset.append(dffinal['action'].iloc[i])

In [58]:
l = len(dataset)
trainDataset = dataset[:int(0.8*l)]
testDataset = dataset[int(0.8*l):]

In [59]:
print(len(trainDataset))
print(len(testDataset))

262951
65738

In [60]:
print(trainDataset[0])

['android.net.nsd.STATE_CHANGED', 'android.net.conn.CONNECTIVITY_CHANGE', 'android.net.wifi.STATE_CHANGE', 'android.net.wifi.WIFI_STATE_CHANGED', 'android.net.wifi.p2p.STATE_CHANGED', 'android.net.wifi.supplicant.STATE_CHANGE', 'android.media.ACTION_SCO_AUDIO_STATE_UPDATED', 'android.media.RINGER_MODE_CHANGED', 'android.media.SCO_AUDIO_STATE_CHANGED']

In [61]:
# Convert each sequence (list) into a string (comma-separated)
data = {"sequence": [", ".join(seq) for seq in trainDataset]}

In [62]:
# Create a DataFrame
dffromlist = pd.DataFrame(data)

In [63]:
# Save to CSV inside Google Drive
save_path = "/content/drive/MyDrive/001.PhD/Smartphone/traintest/trainDataset2.csv"
dffromlist.to_csv(save_path, index=False)

In [64]:
# Convert each sequence (list) into a string (comma-separated)
testData = {"sequence": [", ".join(seq) for seq in testDataset]}

In [65]:
# Create a DataFrame
testdffromlist = pd.DataFrame(testData)

In [66]:
# Save to CSV inside Google Drive
save_path = "/content/drive/MyDrive/001.PhD/Smartphone/traintest/testDataset2.csv"
testdffromlist.to_csv(save_path, index=False)